GET http://localhost:3000/products

### create a product

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "apple watch",
    "price": 500
}

### GET a product by id

GET http://localhost:3000/products/60b4b52bf85de528de5a6664
### Update a product by id

PATCH  http://localhost:3000/products/60b4b52bf85de528de5a6664
Content-Type: application/json

{
    "name" : "mew",
    "price": 500  
}



### Delete aproduct by Id

DELETE  http://localhost:3000/products/60b4b52bf85de528de5a6664

### 

GET http://localhost:3000/abc_xyz

###

GET http://localhost:3000/test?name=iMac&price=2339
###

GET http://localhost:3000/test/46142342/Imac

###

POST http://localhost:3000/test/
Content-Type: application/x-www-form-urlencoded

name=Imac&price=499